# Generated by Django 3.0.14 on 2022-03-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=1000)),
                ('payment_choice', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=355)),
            ],
        ),
    ]
